bf16: true
cutoff_len: 2048
dataloader_num_workers: 4
dataset: openhermes2_5_extracted_sample
dataset_dir: /home/hxy/Data-Preparation-Bench/dcai/Data-Preparation-Bench/data_selection/output/my_filter_task
ddp_timeout: 180000000
do_train: true
finetuning_type: lora
gradient_accumulation_steps: 8
learning_rate: 0.0001
logging_steps: 10
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_samples: 1000
model_name_or_path: Qwen/Qwen2.5-7B-Instruct
num_train_epochs: 3.0
output_dir: /home/hxy/Data-Preparation-Bench/dcai/Data-Preparation-Bench/data_selection/output/my_filter_task/adapter_model
overwrite_output_dir: true
per_device_train_batch_size: 1
plot_loss: true
preprocessing_num_workers: 16
report_to: none
resume_from_checkpoint: null
save_only_model: false
save_steps: 500
stage: sft
template: qwen3_nothink
trust_remote_code: true
warmup_ratio: 0.1
