name: "dfa_qwen2.5_test"
output_root: "./output"

filter:
  type: "agent"
  method: "dfa"
  step: 1
  args:
    train_file: "dataset/intermediate/openhermes2_5_extracted_sample/openhermes2_5_extracted_sample_extracted.jsonl"
    filtered_file: "final_filtered_file.jsonl"
    api_key: "sk-URhU1qxF5iVuW2ZZND5fI0pQcuESJyBt33dv4WGf3JY9dZbI"
    api_url: "http://172.96.141.132:3001/v1"
    target: "数据过滤"
    writer_target: "生成可执行代码并保存过滤后的训练数据"

train:
  model_path: "Qwen/Qwen2.5-7B-Instruct"
  config_profile: "configs/lora_sft.yaml"
  template: "qwen3_nothink"
eval:
  tasks: 
    - "mmlu"
  num_fewshot: 0          
  batch_size: 4           
  device: "cuda:0"      