dataset: dataset_cherry_llm_20260406_174313
dataset_dir: /home/hxy/dcai/data_selection/output/data_selection/dataset_cherry_llm_20260406_174313
output_dir: /home/hxy/dcai/data_selection/output/train_and_eval/dataset_cherry_llm_20260406_174313/model
model_name_or_path: Qwen/Qwen2.5-7B
trust_remote_code: true
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
template: qwen3_nothink
cutoff_len: 2048
max_samples: 1000
preprocessing_num_workers: 16
dataloader_num_workers: 4
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 0.0001
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: false
ddp_timeout: 180000000
resume_from_checkpoint: null
