output_root: "./output"
method: "dfa"
step: -1

args:
  filtered_file: "final_filtered_file.jsonl"
  api_key: "sk-URhU1qxF5iVuW2ZZND5fI0pQcuESJyBt33dv4WGf3JY9dZbI"
  api_url: "http://172.96.141.132:3001/v1/"
  target: "基于评估质量、难度、复杂度、多样性等指标，过滤筛选数据"
  writer_target: "生成可执行的pipeline代码"